OK_FORMAT = True

test = {   'name': 'q2_2_1',
    'points': [0, 0, 0, 1, 4],
    'suites': [   {   'cases': [   {   'code': '>>> import numpy as np\n>>> type(book_title_words) == np.ndarray\nTrue',
                                       'failure_message': "It looks like you didn't make an array.",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> not any([',' in text for text in book_title_words])\nTrue",
                                       'failure_message': 'It looks like you included commas in the text. The three pieces of text in the array should be "Eats" "Shoots" and "and Leaves".',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> 'and ' in book_title_words.item(2)\nTrue",
                                       'failure_message': 'It looks like you didn\'t include both words in the last piece of text.  It should be the actual string "and Leaves"',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> len(book_title_words)\n3', 'hidden': False, 'locked': False},
                                   {   'code': ">>> book_title_words.item(0) == 'Eats' and book_title_words.item(1) == 'Shoots' and (book_title_words.item(2) == 'and Leaves')\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
